// src/lib/games.js
// Trending kid-friendly multiplayer mini-games for GameZone Kids platform

export const games = [
  {
    id: 'battle-quiz',
    title: 'Battle Quiz Royale',
    subtitle: 'Inspired by trending trivia formats',
    emoji: '🧠',
    gradient: ['#7DF9FF', '#BF5AF2'],
    tag: 'hot',
    tagLabel: '🔥 #1 Trending',
    players: '2,841',
    maxPlayers: 4,
    ageRange: '8–15',
    duration: '5 min',
    description: 'Race against 3 friends answering rapid-fire trivia. Minecraft facts, Roblox lore, science & pop culture. First to 10 wins!',
    features: ['Live leaderboard', 'Power-ups', 'Custom rooms', 'Chat'],
    category: 'Brain',
    rating: 4.9,
    reviews: '12.4k'
  },
  {
    id: 'island-builder',
    title: 'Island Builder Clash',
    subtitle: 'Inspired by Minecraft & Animal Crossing',
    emoji: '🏝️',
    gradient: ['#30D158', '#FFD60A'],
    tag: 'hot',
    tagLabel: '🌊 Fan Fav',
    players: '3,102',
    maxPlayers: 4,
    ageRange: '8–15',
    duration: '10 min',
    description: 'Build and defend your island in real-time. Collect resources, craft structures, and vote for the best build at the end!',
    features: ['Real-time co-op', 'Voice chat', 'Voting system', 'Weekly themes'],
    category: 'Creative',
    rating: 4.8,
    reviews: '9.1k'
  },
  {
    id: 'squid-dash',
    title: 'Squid Dash',
    subtitle: 'Inspired by battle royale mini-games',
    emoji: '🦑',
    gradient: ['#FF375F', '#FF9F0A'],
    tag: 'new',
    tagLabel: '⚡ New Drop',
    players: '1,990',
    maxPlayers: 6,
    ageRange: '9–15',
    duration: '3 min',
    description: 'Obstacle course race where only 1 player survives each round. Dodge traps, slide under barriers, outrun others!',
    features: ['6-player lobby', 'Elimination rounds', 'Custom skins', 'Replay sharing'],
    category: 'Action',
    rating: 4.7,
    reviews: '7.2k'
  },
  {
    id: 'ink-arena',
    title: 'Ink Arena',
    subtitle: 'Inspired by Splatoon's ink mechanic',
    emoji: '🎨',
    gradient: ['#BF5AF2', '#7DF9FF'],
    tag: 'hot',
    tagLabel: '🎨 Creative',
    players: '2,230',
    maxPlayers: 4,
    ageRange: '8–15',
    duration: '4 min',
    description: 'Paint the arena in your team's color! Safe, ink-slinging fun with 2v2 team battles. Cover the most tiles to win!',
    features: ['2v2 teams', 'Power splashes', 'Weekly maps', 'Safe for all ages'],
    category: 'Team',
    rating: 4.9,
    reviews: '15.6k'
  },
  {
    id: 'word-warp',
    title: 'Word Warp Speed',
    subtitle: 'Inspired by Wordle & competitive spelling',
    emoji: '📝',
    gradient: ['#FFD60A', '#30D158'],
    tag: 'new',
    tagLabel: '✨ Edu Pick',
    players: '1,405',
    maxPlayers: 4,
    ageRange: '8–14',
    duration: '4 min',
    description: 'Scrambled letters fly onto the screen — first to build the longest valid word scores big. Fun vocabulary challenge!',
    features: ['Dictionary validated', 'Hint tokens', 'Daily challenge', 'Parent reports'],
    category: 'Brain',
    rating: 4.6,
    reviews: '5.3k'
  },
  {
    id: 'monster-race',
    title: 'Monster Kart Race',
    subtitle: 'Inspired by Monster Hunter Stories',
    emoji: '🏎️',
    gradient: ['#FF9F0A', '#FF375F'],
    tag: 'hot',
    tagLabel: '🏆 Popular',
    players: '4,017',
    maxPlayers: 6,
    ageRange: '8–15',
    duration: '6 min',
    description: 'Race your monster kart across 8 fantasy tracks. Use item boxes to blast friends with silly power-ups. Pure chaos fun!',
    features: ['8 tracks', 'Power-ups', 'Monster skins', 'Ghost replay'],
    category: 'Racing',
    rating: 4.8,
    reviews: '18.2k'
  },
  {
    id: 'draw-it',
    title: 'DrawIt Together',
    subtitle: 'Inspired by Gartic Phone trends',
    emoji: '✏️',
    gradient: ['#7DF9FF', '#30D158'],
    tag: 'live',
    tagLabel: '🎭 Comedy Hit',
    players: '5,341',
    maxPlayers: 8,
    ageRange: '8–15',
    duration: '8 min',
    description: 'Draw a word and friends guess in seconds! Then your drawing gets passed on — see how wildly the story changes!',
    features: ['8-player rooms', 'Animated canvas', 'Emoji reactions', 'Weekly packs'],
    category: 'Creative',
    rating: 5.0,
    reviews: '24.7k'
  },
  {
    id: 'math-duel',
    title: 'Math Speed Duel',
    subtitle: 'Learn-while-you-play format',
    emoji: '⚡',
    gradient: ['#BF5AF2', '#FF375F'],
    tag: 'new',
    tagLabel: '🎓 School Fav',
    players: '987',
    maxPlayers: 4,
    ageRange: '8–15',
    duration: '5 min',
    description: 'Buzzer-style math battles! Addition to pre-algebra. Choose difficulty, race to answer 10 questions first, earn XP!',
    features: ['3 difficulty modes', 'School leaderboard', 'Progress tracking', 'Teacher mode'],
    category: 'Brain',
    rating: 4.7,
    reviews: '6.8k'
  }
];

export const categories = ['All', 'Brain', 'Creative', 'Action', 'Team', 'Racing'];

export const stats = [
  { value: '47K+', label: 'Kids Playing Daily', icon: '🌍' },
  { value: '8',    label: 'Mini Games',          icon: '🎮' },
  { value: '100%', label: 'Safe & Moderated',    icon: '🛡️' },
  { value: '4.9★', label: 'Parent Rating',        icon: '⭐' }
];
